<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
           xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
           elementFormDefault="qualified">
    <xs:complexType name="BusinessDocumentType">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
        <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
    <xs:element name="Invoice" type="BusinessDocumentType"/>
    <xs:element name="DespatchAdvice" type="BusinessDocumentType"/>
    <xs:element name="Document" type="BusinessDocumentType"/>
</xs:schema>
