package com.nexa.api.shared.presentation.error;

public enum ApiErrorCode {
	VALIDATION_ERROR,
	INVALID_REQUEST,
	RESOURCE_NOT_FOUND,
	METHOD_NOT_ALLOWED,
	UNAUTHORIZED,
	FORBIDDEN,
	AUTHENTICATION_REQUIRED,
	AUTHENTICATION_FAILED,
	REFRESH_SESSION_INVALID,
	ACCESS_CONTEXT_INVALID,
	WORKSPACE_ACCESS_DENIED,
	SURFACE_ACCESS_DENIED,
	PERMISSION_DENIED,
	ORIGIN_NOT_ALLOWED,
	CATALOG_ITEM_NOT_FOUND,
	INVALID_CATALOG_QUERY,
	ROLE_TRANSITION_NOT_ALLOWED,
	LAST_ACTIVE_OWNER_REQUIRED,
	CONCURRENCY_CONFLICT,
	PRECONDITION_REQUIRED,
	INTERNAL_ERROR
}
